picard: /seq/software/picard-public/2.24.2/picard.jar
dropseq_dir: /broad/macosko/bin/dropseq-tools-2.4.0
reference_dir: /broad/macosko/reference
workflow_dir: /broad/macosko/data/workflows/flowcell
library_dir: /broad/macosko/data/libraries
gsecret_name: 'projects/velina-208320/secrets/sequencing-credentials/versions/latest'
gsheet_id: 1kwnKrkbl80LyE9lND0UZZJXipL4yfBbGjkTe6hcwJic
worksheet: 'Experiment Log'
gs_path: macosko_data/libraries
