picard: /seq/software/picard-public/2.24.2/picard.jar
dropseq_dir: /broad/macosko/bin/dropseq-tools-2.4.0
reference_dir: /broad/macosko/reference
workflow_dir: /broad/macosko/data/workflows/flowcell
library_dir: /broad/macosko/data/libraries
gsheet_id: 1kwnKrkbl80LyE9lND0UZZJXipL4yfBbGjkTe6hcwJic
worksheet: 'Experiment Log'
gs_path: gs://macosko_data/libraries
